### ISSUE TITLE
App Store Safe?

### ISSUE THREAD

**Issue by danmartyn** [natanrolnik/NRTouchPoints#4]
Do we need to remove this before sending to the app store? If we use the flag to have it off by default, and only turn on in certain instances, will Apple still reject the app? It doesn't seem to be doing anything that's using private APIs?

**Comment by natanrolnik** [comment]
It doesn't use any private API - so you should not have any problems with App Store rejections.
I personally would only enable turning it on in debug (by setting `#ifdef DEBUG` before and `#endif`after it).
